### ISSUE TITLE
김시원 백엔드 6주차 배포 과제 제출입니다.

### ISSUE THREAD

**Issue by seaniiio** [likelion-Inha-12/seaniiio#10]
## 1. 배포 성공한 화면
<img width="1403" alt="1" src="https://github.com/likelion-Inha-12/seaniiio/assets/121426422/513f68f9-e4fd-41c7-b7b5-bdc51f028f51">

## 2. 배포할 때 사용한 인스턴스 정보가 담긴 화면
<img width="1512" alt="2" src="https://github.com/likelion-Inha-12/seaniiio/assets/121426422/fc50f43f-bc0b-4ab2-bae4-6808a812c108">

**Comment by juwon0403** [comment]
단톡방에 추가 공지한대로 포트 번호를 뺀 IP주소로 접속한 화면을 제출해주세용~

인스턴스 정보는 잘 캡처해주셨어요!!

**Comment by seaniiio** [comment]
수정했습니다!

**Comment by juwon0403** [comment]
역시 과제 1등은 시원님.. 수고하셨서용!!
