### ISSUE TITLE
김시원 백엔드 7주차 과제 제출입니다.

### ISSUE THREAD

**Issue by seaniiio** [likelion-Inha-12/seaniiio#13]
# 1

## ✅ URL v.s. Origin v.s. Domain 각각의 개념은 무엇이고, 세 키워드 간의 관계는 어떻게 될까요?

URL : 인터넷 상에서 자원의 위치를 나타내는 주소로, **Protocol://Host:Port/Path?Parameter#Fragment** 형식으로 나타낸다.

Origin : URL 구조에서 Protocol, Host, Port를 합친 것을 말한다. 주로 보안과 관련된 이유로 **자원의 출처를 식별**하는 역할을 한다.

Domain : URL 구조에서 서버의 이름을 나타낸다. **IP 주소와 매핑되어 웹 브라우저가 해당 서버에 접근할 수 있게 한다.**

Origin은 URL의 구성 요소이고, Domain은 Origin의 구성요소이다. 이들은 자원에 안전하게 접근할 수 있게 한다.

## ✅ 같은 출처? 다른 출처?
`https://lionz12.netlify.app`과 아래의 URL을 비교하여 같은 출처인지, 다른 출처인지 그리고 그 이유는 무엇인지에 대해 간략하게 적어주세요!

`https://lionz12.netlify.app/homework` : Protocol, Host, Port가 같기 때문에, 같은 출처이다. (포트번호는 생략되었다고 판단)

`https://lionz12.netlify.app/homework-submit/69` : Protocol, Host, Port가 같기 때문에, 같은 출처이다. 

`http://lionz12.netlify.app/homework` : Protocol이 다르므로, 다른 출처이다.

`https://lionz12.seminar.com` :  Host가 다르므로, 다른 출처이다.

## ✅ `Access-Control-Allow-Origin : *` 는 무슨 의미일지, 그리고 이렇게 설정한다면 무슨 일이 일어날지 생각해보세요!

`Access-Control-Allow-Origin`는 어떤 Origin에서의 요청을 허용할 것인지를 명시할 때 사용한다.

`Access-Control-Allow-Origin : *`은 모든 Origin에서의 요청을 허용한다는 의미이고, 모든 Origin에서 자유롭게 리소스에 접근할 수 있게 되므로, 보안상의 문제가 생길 수 있다.

따라서 민감한 데이터가 포함된 리소스에는 사용하지 않는 것이 좋다.

## ✅ CORS와 같이 어플리케이션에서 사용자 정보를 탈취하는 것을 막기 위한 정책인 CSRF(Cross-Site Request Forgery)가 무엇인지, django에서는 CSRF 공격을 어떻게 방어하는지도 알아보면 좋을 것 같아요

CSRF Attack은 사용자가 자신의 의지와는 무관하게 공격자가 의도한 행위(수정, 삭제, 등록 등)를 특정 웹사이트에 요청하게 하는 공격이다.

이를 막기 위해서 CSRF 토큰 사용할 수 있다. CSRF 토큰은 서버가 생성하여 사용자 세션과 연결된 형태로 클라이언트에 제공되는 비밀 값이다. 웹 어플리케이션의 모든 중요한 변경 작업을 수행하는 요청에 CSRF 토큰을 포함시켜야 한다. 공격자는 이 토큰을 알지 못하기 때문에 유효한 요청을 위조할 수 없다.

이러한 공격을 막기 위해 django에서는 CsrfViewMiddleware라는 미들웨어를 통해 CSRF 보호 기능을 제공한다. 이 미들웨어는 모든 POST, PUT, DELETE 요청에 대해 CSRF 토큰이 포함되어 있는지를 확인한다.

# 2
<img width="1422" alt="스크린샷 2024-05-22 오후 1 57 26" src="https://github.com/likelion-Inha-12/seaniiio/assets/121426422/bc222961-3fc3-42aa-88df-19ee9a0c6fb0">

**Comment by juwon0403** [comment]
깔끔하게 정리 잘해주셨어용 ㅎㅎ
csrf 공격에 대한 방어에 대한 다양한 방법들이 존재하는데, 다른 아기사자분들 레포도 한번 참고하시면 도움되실 것 같아요!

과제하느라 수고하셨슴니당~~
